## DISCLAIMERS: This NK Landscape Generation Package is quite basic for now.  This package MAY be updated or maintained based on the whims of RAs in the CSS Lab at NEU's Network Science Institute.  

### There are a few future-looking additions to this package that are not fully implemented. 
### MODIFY PREDEFINED ARGUMENTS AT YOUR OWN RISK (i.e. the 'base' argument in nklsgen.nk_landscapes() may not work for any value other than 2)

### Simplest Application
The primary function, generate_landscapes(), requires 3 inputs:
1. N => defines landscape size
2. K => defines landscape roughness
3. num_of_ls => defines number of landscapes created

The output will be an np.array containing randomly generated landscapes, with each landscape as a dictionary. <br>

Each key, value pair in a landscape dictionary represents a single location and it's fitness value. The locations are binary strings.  Each dictionary should contain 2^N entries (given the base of 2). <br>

In [4]:
import nklsgen

N, K, num_of_ls = 3, 1, 1
landscapes = nklsgen.generate_landscapes(N, K, num_of_ls)

landscapes[0]

{'000': 1.0,
 '001': 0.7626477881494286,
 '010': 0.237352211572279,
 '011': 0.0,
 '100': 0.3419241539309924,
 '101': 0.4892473488109021,
 '110': 0.1639162497309352,
 '111': 0.3112394446108449}

## Preprocessing

The generate_landscapes() function adds two forms of preprocessing used for our specific applications. Part of the preprocessing scales all values in each landscape such that the minimum is 0 and the maximum is 1. The second step of preprocessing is modifying the landscape data structure from np.array to dictionary. <br>

Without preprocessing, each landscape has randomly generated values not guaranteed cover the [0,1] range. 

Without preprocessing, each landscape remains in np.array format where each row contains both a location on the landscape and the value at that location:
- The first N values in each row are the binary location code
- The last value is the fitness value of that location

Learn more about the unprocessed landscape structure in the docstring for the nklsgen.nk_landscapes() function. 

In [20]:
### HERE IS THE FULL EXPLANATION OF THE UNPROCESSED NP.ARRAY LANDSCAPE STRUCTURE
# help(nklsgen.nk_landscapes)

In [9]:
# Landscape example with preprocessing=False (try it with true too!)
N, K, num_of_ls = 3, 1, 1
landscapes = nklsgen.generate_landscapes(N, K, num_of_ls, preprocessed=False)
# landscapes = nklsgen.generate_landscapes(N, K, num_of_ls, preprocessed=True)

# Isolate first landscape
landscape = landscapes[0]

# Landscape Min/Max
print(f'The minimum value in this landscape is : {min(landscape[:,-1:])}')
print(f'The maximum value in this landscape is : {max(landscape[:,-1:])}')

The minimum value in this landscape is : [0.41961083]
The maximum value in this landscape is : [0.76467563]


In [10]:
print(landscape)

[[0.         0.         0.         0.62056487]
 [0.         0.         1.         0.66544039]
 [0.         1.         0.         0.51616509]
 [0.         1.         1.         0.56104061]
 [1.         0.         0.         0.41961083]
 [1.         0.         1.         0.66646676]
 [1.         1.         0.         0.5178197 ]
 [1.         1.         1.         0.76467563]]


In [11]:
print(f'The first location in this landscape is : {landscape[0][0:N]}')
print(f'The first value in this landscape is: {landscape[0][-1:]}')

The first location in this landscape is : [0. 0. 0.]
The first value in this landscape is: [0.62056487]


## There and Back Again

nklsgen contains a two conversion functions needed for preprocessing.  These functions are: 
1. bin_to_str() => converting a list of binary values (found in unprocessed np.array landscapes) to a string. 
2. str_to_bin() => converting a string of binary values back into a list. 

These are useful for us, mostly for indexing purposes, but I wanted to put an example here for clarity. 

In [23]:
## To convert np.array landscape format to str use bin_to_str()

# Grab the location from a specific row in your landscape (be sure to )
loc_bin = landscape[0,0:N].copy()
print(f'Location information in list format: {loc_bin}')

# Convert to str format
loc_str = nklsgen.bin_to_str(loc_bin)
print(f'Location information in string format: {loc_str}')

Location information in list format: [0. 0. 0.]
Location information in string format: 000


In [27]:
## To convert str format back into list format use str_to_bin()

print(f'Location information in string format: {loc_str}')

loc_bin2 = nklsgen.str_to_bin(loc_str)
print(f'Location information in list format: {loc_bin2}')

Location information in string format: 000
Location information in list format: [0, 0, 0]
